server:
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petclinic?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: petclinic
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true  
    show-sql: true
    generate-ddl: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false  

